-- Consultar Tablas --
SELECT * FROM address;
SELECT * FROM customers;
SELECT * FROM ingredient;
SELECT * FROM inventory;
SELECT * FROM item;
SELECT * FROM orders;
SELECT * FROM recipe;
SELECT * FROM rota;
SELECT * FROM shift;
SELECT * FROM staff;
SELECT * FROM auditoria_clientes;
SELECT * FROM registro_transacciones_inventario;
SELECT * FROM registro_precio_productos;